[binaries]
c = ['clang-cl', '-fuse-ld=lld', '--target=x86_64-pc-windows-msvc', '/winsdkdir', '/opt/win-sdk/10.0.22621/sdk', '/vctoolsdir', '/opt/win-sdk/10.0.22621/crt']
cpp = ['clang-cl', '-fuse-ld=lld', '--target=x86_64-pc-windows-msvc', '/winsdkdir', '/opt/win-sdk/10.0.22621/sdk', '/vctoolsdir', '/opt/win-sdk/10.0.22621/crt']
ar = 'llvm-lib'
strip = 'llvm-strip'
windres = 'llvm-rc'
exe_wrapper = 'wine64'

[built-in options]
# Static linking: /MTd for Debug, /MT for Release
b_vscrt = 'static_from_buildtype'
cpp_std='c++latest'
c_link_args = [
  '/libpath:/opt/win-sdk/10.0.22621/crt/lib/x64',
  '/libpath:/opt/win-sdk/10.0.22621/sdk/lib/10.0.26100/ucrt/x64',
  '/libpath:/opt/win-sdk/10.0.22621/sdk/lib/10.0.26100/um/x64',
  '/ignore:4099' # Suppress LNK4099 warnings for missing upstream MSVC CRT PDBs
  ]


cpp_link_args = [
  '/libpath:/opt/win-sdk/10.0.22621/crt/lib/x64',
  '/libpath:/opt/win-sdk/10.0.22621/sdk/lib/10.0.26100/ucrt/x64',
  '/libpath:/opt/win-sdk/10.0.22621/sdk/lib/10.0.26100/um/x64',
  '/ignore:4099' # Suppress LNK4099 warnings for missing upstream MSVC CRT PDBs
  ]

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
